drop table if exists bikes;
create table bikes
(
    id            int8 generated by default as identity,
    cost_per_hour int4,
    model         varchar(255),
    name          varchar(255),
    primary key (id)
)
