drop table if exists orders;
create table orders
(
    id         int8 generated by default as identity,
    cost       int8 not null,
    date       date,
    status     varchar(255),
    time_start time,
    time_stop  time,
    bike_id    int8 not null,
    client_id  int8 not null,
    primary key (id)
)
